// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopNN.Entities;

#nullable disable

namespace ShopNN.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ShopNN.Entities.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("ShopNN.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f04972bf-3d1e-4866-bc4a-24789221ac97",
                            Email = "admin@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEHMSRBNB0wxlsAPbfPnV99xKQ1F5cLZ2ytUNxnBmh33maVdfM48qEEseGaWvtDjoSQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "STATIC-SECURITY-STAMP-FOR-SEED-DATA",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("ShopNN.Entities.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("ShopNN.Entities.CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("ShopNN.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=800",
                            Name = "Luxury Watches"
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?w=800",
                            Name = "Sport Watches"
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "https://images.unsplash.com/photo-1434493907317-a46b5bc78344?w=800",
                            Name = "Smart Watches"
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=800",
                            Name = "Classic Watches"
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=800",
                            Name = "Fashion Watches"
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "https://images.unsplash.com/photo-1612817159949-195b6eb9e31a?w=800",
                            Name = "Dive Watches"
                        },
                        new
                        {
                            Id = 7,
                            ImageUrl = "https://images.unsplash.com/photo-1587925358603-c2eea5305bbc?w=800",
                            Name = "Pilot Watches"
                        });
                });

            modelBuilder.Entity("ShopNN.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ShopNN.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("ShopNN.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("ShopNN.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            CategoryId = 1,
                            Description = "Đồng hồ lặn huyền thoại với vỏ Oystersteel 41mm, mặt số đen Cerachrom, chống nước 300m. Bộ máy Calibre 3235 tự động, dự trữ năng lượng 70 giờ. Dây đeo Oyster với khóa Oysterlock an toàn và hệ thống điều chỉnh Glidelock.",
                            ImageUrl = "https://images.unsplash.com/photo-1622434641406-a158123450f9?w=800",
                            Name = "Rolex Submariner Date 126610LN",
                            Price = 245000000m,
                            Stock = 3
                        },
                        new
                        {
                            Id = 102,
                            CategoryId = 1,
                            Description = "Biểu tượng của tốc độ và đẳng cấp. Vỏ Oystersteel 40mm, bezel Cerachrom đen, mặt số Panda trắng. Bộ máy Calibre 4131 chronograph, dự trữ năng lượng 72 giờ. Chống nước 100m.",
                            ImageUrl = "https://images.unsplash.com/photo-1547996160-81dfa63595aa?w=800",
                            Name = "Rolex Daytona 126500LN",
                            Price = 385000000m,
                            Stock = 1
                        },
                        new
                        {
                            Id = 103,
                            CategoryId = 1,
                            Description = "Chiếc đồng hồ thể thao sang trọng kinh điển. Vỏ thép không gỉ 40mm, mặt số xanh gradient, dây thép tích hợp. Bộ máy Calibre 26-330 S C tự động, chống nước 120m. Thiết kế bởi Gerald Genta.",
                            ImageUrl = "https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=800",
                            Name = "Patek Philippe Nautilus 5711/1A-010",
                            Price = 2850000000m,
                            Stock = 1
                        },
                        new
                        {
                            Id = 104,
                            CategoryId = 1,
                            Description = "Vỏ thép không gỉ 41mm, mặt số xanh Petite Tapisserie. Bộ máy Calibre 4302 tự động, dự trữ năng lượng 70 giờ. Thiết kế octagon với 8 ốc vít hexagonal đặc trưng. Chống nước 50m.",
                            ImageUrl = "https://images.unsplash.com/photo-1614164185128-e4ec99c436d7?w=800",
                            Name = "Audemars Piguet Royal Oak 15500ST",
                            Price = 1250000000m,
                            Stock = 2
                        },
                        new
                        {
                            Id = 105,
                            CategoryId = 1,
                            Description = "Chiếc đồng hồ đầu tiên lên Mặt Trăng. Vỏ thép 42mm, mặt số đen, kính Hesalite. Bộ máy Calibre 3861 METAS lên dây cót thủ công, dự trữ 50 giờ. Chronograph với tachymeter bezel.",
                            ImageUrl = "https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=800",
                            Name = "Omega Speedmaster Moonwatch Professional",
                            Price = 152000000m,
                            Stock = 5
                        },
                        new
                        {
                            Id = 106,
                            CategoryId = 6,
                            Description = "Vỏ thép không gỉ 42mm, mặt số ceramic xanh biển. Bộ máy Master Chronometer 8800, chống từ 15,000 gauss. Chống nước 300m, van thoát khí helium. Dây cao su hoặc thép.",
                            ImageUrl = "https://images.unsplash.com/photo-1612817159949-195b6eb9e31a?w=800",
                            Name = "Omega Seamaster Diver 300M",
                            Price = 125000000m,
                            Stock = 7
                        },
                        new
                        {
                            Id = 107,
                            CategoryId = 2,
                            Description = "Cấu trúc Carbon Core Guard siêu bền. Chống bùn, chống va đập, chống rung. Triple Sensor (la bàn, đo cao, khí áp/nhiệt độ). Năng lượng mặt trời, đồng bộ sóng radio Multiband 6.",
                            ImageUrl = "https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?w=800",
                            Name = "Casio G-Shock Mudmaster GWG-2000",
                            Price = 18500000m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 108,
                            CategoryId = 2,
                            Description = "Thiết kế bát giác mỏng nhất dòng G-Shock chỉ 11.8mm. Vỏ nhựa carbon, chống va đập. Hiển thị analog-digital kết hợp. Pin CR2016 thời lượng 3 năm. Chống nước 200m.",
                            ImageUrl = "https://images.unsplash.com/photo-1508685096489-77a46807e624?w=800",
                            Name = "Casio G-Shock GA-2100-1A1 'CasiOak'",
                            Price = 3200000m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 109,
                            CategoryId = 6,
                            Description = "Tái bản mẫu đồng hồ lặn đầu tiên của Seiko. Vỏ thép 40.5mm, mặt số xanh gradient. Bộ máy 6R35 tự động, dự trữ 70 giờ. Kính sapphire, chống nước 200m. Dây silicone.",
                            ImageUrl = "https://images.unsplash.com/photo-1509048191080-d2984bad6ad5?w=800",
                            Name = "Seiko Prospex SPB143 '62MAS Reissue'",
                            Price = 28500000m,
                            Stock = 12
                        },
                        new
                        {
                            Id = 110,
                            CategoryId = 2,
                            Description = "Đồng hồ thể thao GPS cao cấp nhất của Garmin. Màn hình MIP 1.4 inch, sạc năng lượng mặt trời. Bản đồ TopoActive, đèn LED tích hợp. Pin lên đến 37 ngày (GPS), cảm biến SpO2, nhịp tim quang học.",
                            ImageUrl = "https://images.unsplash.com/photo-1517502884422-41eaead166d4?w=800",
                            Name = "Garmin Fenix 7X Pro Solar",
                            Price = 22900000m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 111,
                            CategoryId = 3,
                            Description = "Vỏ titanium 49mm, màn hình OLED 2000 nits. Chip S9, Double Tap, GPS L1+L5 chính xác cao. Chống nước 100m, đạt chuẩn EN13319 cho lặn. Pin 36 giờ sử dụng bình thường, 72 giờ tiết kiệm pin.",
                            ImageUrl = "https://images.unsplash.com/photo-1434493907317-a46b5bc78344?w=800",
                            Name = "Apple Watch Ultra 2",
                            Price = 21990000m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 112,
                            CategoryId = 3,
                            Description = "Vòng bezel xoay cổ điển, màn hình Super AMOLED 1.5 inch. Chip Exynos W930, Wear OS, theo dõi giấc ngủ nâng cao. Cảm biến BioActive, đo nhiệt độ da, ECG, huyết áp. Pin 425mAh.",
                            ImageUrl = "https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=800",
                            Name = "Samsung Galaxy Watch 6 Classic 47mm",
                            Price = 9490000m,
                            Stock = 35
                        },
                        new
                        {
                            Id = 113,
                            CategoryId = 3,
                            Description = "Màn hình AMOLED 1.4 inch sáng rõ. Theo dõi sức khỏe toàn diện: Body Battery, Sleep Coach, HRV, Nap Detection. Hơn 30 ứng dụng thể thao tích hợp. Pin lên đến 14 ngày. Hỗ trợ nghe gọi Bluetooth.",
                            ImageUrl = "https://images.unsplash.com/photo-1544117519-31731f4fcdde?w=800",
                            Name = "Garmin Venu 3",
                            Price = 11990000m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 114,
                            CategoryId = 4,
                            Description = "Thiết kế retro-chic lấy cảm hứng từ thập niên 70. Vỏ thép 40mm, mặt số xanh lá waffle. Bộ máy Powermatic 80 tự động, dự trữ 80 giờ. Kính sapphire chống xước. Chống nước 100m.",
                            ImageUrl = "https://images.unsplash.com/photo-1533139502658-0198f920d8e8?w=800",
                            Name = "Tissot PRX Powermatic 80",
                            Price = 16200000m,
                            Stock = 18
                        },
                        new
                        {
                            Id = 115,
                            CategoryId = 4,
                            Description = "Đồng hồ quân đội kinh điển. Vỏ thép 38mm, mặt số đen matte. Bộ máy H-50 lên dây cót thủ công, dự trữ 80 giờ. Dây vải NATO olive. Kính sapphire, chống nước 50m.",
                            ImageUrl = "https://images.unsplash.com/photo-1548171915-e79a380a2a4b?w=800",
                            Name = "Hamilton Khaki Field Mechanical",
                            Price = 12500000m,
                            Stock = 14
                        },
                        new
                        {
                            Id = 116,
                            CategoryId = 4,
                            Description = "Vỏ thép 40mm, mặt số trắng kem với chỉ báo trăng tròn lúc 6h. Bộ máy L899 tự động (base ETA), dự trữ 72 giờ. Kim xanh thép, index La Mã. Dây da cá sấu đen.",
                            ImageUrl = "https://images.unsplash.com/photo-1542496658-e33a6d0d50f6?w=800",
                            Name = "Longines Master Collection Moonphase",
                            Price = 58000000m,
                            Stock = 6
                        },
                        new
                        {
                            Id = 117,
                            CategoryId = 5,
                            Description = "Thiết kế minimalist thanh lịch cho phái nữ. Vỏ thép mạ vàng hồng 32mm, mặt số trắng tinh khiết. Bộ máy Miyota quartz Nhật Bản. Dây da đen Italian. Chống nước 30m.",
                            ImageUrl = "https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=800",
                            Name = "Daniel Wellington Petite Sheffield 32mm",
                            Price = 4590000m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 118,
                            CategoryId = 5,
                            Description = "Kết hợp kim analog truyền thống và màn hình E-Ink. Theo dõi nhịp tim, SpO2, giấc ngủ. Pin 2 tuần. Kết nối Bluetooth, thông báo điện thoại. Vỏ thép 44mm, chống nước 50m.",
                            ImageUrl = "https://images.unsplash.com/photo-1434056886845-dbe89f0b9571?w=800",
                            Name = "Fossil Gen 6 Hybrid Wellness Edition",
                            Price = 5990000m,
                            Stock = 22
                        },
                        new
                        {
                            Id = 119,
                            CategoryId = 7,
                            Description = "Vỏ thép 40mm, mặt số đen matte với triangle index lúc 12h. Bộ máy 32111 tự động (base Sellita), dự trữ 120 giờ. Kính sapphire chống phản chiếu, hệ thống bảo vệ từ trường.",
                            ImageUrl = "https://images.unsplash.com/photo-1587925358603-c2eea5305bbc?w=800",
                            Name = "IWC Pilot's Watch Mark XX",
                            Price = 115000000m,
                            Stock = 4
                        },
                        new
                        {
                            Id = 120,
                            CategoryId = 7,
                            Description = "Biểu tượng hàng không với slide rule bezel. Vỏ thép 43mm, bộ máy in-house B01 chronograph, dự trữ 70 giờ. Mặt số đen với 3 subdial. Chống nước 30m. COSC Chronometer certified.",
                            ImageUrl = "https://images.unsplash.com/photo-1509941943102-10c232535736?w=800",
                            Name = "Breitling Navitimer B01 Chronograph 43",
                            Price = 198000000m,
                            Stock = 3
                        },
                        new
                        {
                            Id = 121,
                            CategoryId = 6,
                            Description = "Vỏ thép 39mm kích thước vintage hoàn hảo. Mặt số đen gilt, bezel đen nhôm. Bộ máy MT5402 COSC tự động, dự trữ 70 giờ. Chống nước 200m. Dây thép riveted style.",
                            ImageUrl = "https://images.unsplash.com/photo-1548169874-53e85f753f1e?w=800",
                            Name = "Tudor Black Bay 58",
                            Price = 89000000m,
                            Stock = 8
                        },
                        new
                        {
                            Id = 122,
                            CategoryId = 6,
                            Description = "Đồng hồ lặn năng lượng ánh sáng, không cần thay pin. Vỏ thép 44mm, mặt số xanh biển. Chống nước 200m ISO 6425. Dạ quang Lumi-Brite mạnh mẽ. Dây polyurethane bền bỉ.",
                            ImageUrl = "https://images.unsplash.com/photo-1506193095-80a5798431c7?w=800",
                            Name = "Citizen Promaster Eco-Drive BN0151-09L",
                            Price = 7200000m,
                            Stock = 28
                        },
                        new
                        {
                            Id = 123,
                            CategoryId = 4,
                            Description = "Dress watch giá tốt nhất phân khúc. Vỏ thép 40.5mm, mặt số kem vintage, kim blued hands. Bộ máy F6722 tự động, dự trữ 40 giờ. Kính mineral dome. Dây da nâu.",
                            ImageUrl = "https://images.unsplash.com/photo-1455397792935-60e8e4d4c0a5?w=800",
                            Name = "Orient Bambino Version 2 FAC00005W0",
                            Price = 4800000m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 124,
                            CategoryId = 3,
                            Description = "Màn hình AMOLED 1.43 inch, vỏ bezel có thể thay thế. HyperOS, hỗ trợ eSIM, GPS độc lập. Theo dõi 150+ bài tập, SpO2 24/7. Pin 486mAh, sử dụng 15 ngày. Chống nước 5ATM.",
                            ImageUrl = "https://images.unsplash.com/photo-1461141346587-763ab02bced9?w=800",
                            Name = "Xiaomi Watch S3",
                            Price = 3290000m,
                            Stock = 45
                        },
                        new
                        {
                            Id = 125,
                            CategoryId = 2,
                            Description = "Dòng đồng hồ tự động huyền thoại của Seiko. Vỏ thép 42.5mm, mặt số đen sunburst. Bộ máy 4R36 tự động, dự trữ 41 giờ, hacking & hand-winding. Chống nước 100m. Day-Date hiển thị.",
                            ImageUrl = "https://images.unsplash.com/photo-1539874754764-5a96559165b0?w=800",
                            Name = "Seiko 5 Sports SRPD55K1",
                            Price = 6800000m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 126,
                            CategoryId = 2,
                            Description = "Biểu tượng đua xe thể thao. Vỏ thép 44mm, mặt số đen với subdials bạc. Bộ máy Heuer 02 COSC in-house chronograph, dự trữ 80 giờ. Kính sapphire, caseback transparent.",
                            ImageUrl = "https://images.unsplash.com/photo-1600721391776-b5cd0e0048f2?w=800",
                            Name = "TAG Heuer Carrera Chronograph 44mm",
                            Price = 128000000m,
                            Stock = 5
                        },
                        new
                        {
                            Id = 127,
                            CategoryId = 1,
                            Description = "Chiếc đồng hồ đeo tay đầu tiên trong lịch sử (1904). Vỏ thép 35.1mm, mặt số bạc guilloché, số La Mã xanh. Bộ máy 1847 MC tự động. Hệ thống QuickSwitch dây da/thép.",
                            ImageUrl = "https://images.unsplash.com/photo-1526045431048-f857369baa09?w=800",
                            Name = "Cartier Santos de Cartier Medium",
                            Price = 168000000m,
                            Stock = 4
                        },
                        new
                        {
                            Id = 128,
                            CategoryId = 5,
                            Description = "Thiết kế Bauhaus tinh khiết bởi nghệ sĩ Max Bill. Vỏ thép 38mm, mặt số trắng với font số đặc trưng. Bộ máy J800.1 tự động. Kính Plexiglas dome, dây da đen. Chống nước 30m.",
                            ImageUrl = "https://images.unsplash.com/photo-1533139143976-30918502365b?w=800",
                            Name = "Junghans Max Bill Automatic",
                            Price = 28500000m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 129,
                            CategoryId = 7,
                            Description = "Đồng hồ lặn thiết kế vuông độc đáo lấy cảm hứng từ buồng lái máy bay. Vỏ thép 42mm, mặt số đen matte. Bộ máy BR-CAL.302 tự động. Chống nước 300m, bezel xoay một chiều.",
                            ImageUrl = "https://images.unsplash.com/photo-1585123334904-845d60e97b29?w=800",
                            Name = "Bell & Ross BR 03-92 Diver",
                            Price = 98000000m,
                            Stock = 3
                        },
                        new
                        {
                            Id = 130,
                            CategoryId = 2,
                            Description = "Chronograph thể thao kết nối Bluetooth. Vỏ thép carbon 48mm, mặt số đen đa lớp. Năng lượng mặt trời Tough Solar. World time 300 thành phố, đồng bộ thời gian qua smartphone.",
                            ImageUrl = "https://images.unsplash.com/photo-1495856458515-0637185db551?w=800",
                            Name = "Casio Edifice ECB-2000DC-1A",
                            Price = 8500000m,
                            Stock = 18
                        });
                });

            modelBuilder.Entity("ShopNN.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("ShopNN.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("ShopNN.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("ShopNN.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("ShopNN.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShopNN.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("ShopNN.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShopNN.Entities.Cart", b =>
                {
                    b.HasOne("ShopNN.Entities.ApplicationUser", "User")
                        .WithOne("Cart")
                        .HasForeignKey("ShopNN.Entities.Cart", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShopNN.Entities.CartItem", b =>
                {
                    b.HasOne("ShopNN.Entities.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShopNN.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ShopNN.Entities.Order", b =>
                {
                    b.HasOne("ShopNN.Entities.ApplicationUser", null)
                        .WithMany("Orders")
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("ShopNN.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShopNN.Entities.OrderItem", b =>
                {
                    b.HasOne("ShopNN.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShopNN.Entities.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ShopNN.Entities.Payment", b =>
                {
                    b.HasOne("ShopNN.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ShopNN.Entities.Product", b =>
                {
                    b.HasOne("ShopNN.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ShopNN.Entities.RefreshToken", b =>
                {
                    b.HasOne("ShopNN.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShopNN.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Cart");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("ShopNN.Entities.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ShopNN.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ShopNN.Entities.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ShopNN.Entities.Product", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
